import mongoose from 'mongoose'

const FeedSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  feed: {
    type: Object
  },
  feedName: {
    type: String
  },
  audienceName: {
    type: String
  },
  zipTemplate: {
    type: Boolean
  },
  writeManifest: {
    type: Boolean
  },
  templateSizes: {
    type: Array
  },
  templateType: {
    type: String
  }
});

// export the feed object generated by the visualizer form to mongodb
const Feed = mongoose.model("Feed", FeedSchema);
module.exports = Feed;
