import mongoose from 'mongoose'

const FileSchema = new mongoose.Schema({
  name: {
    type: String
  },
  size: {
    type: String
  },
  file: {
    type: String,
    data: Buffer
  },
  path: {
    type: String
  },
  date: {
    type: Date,
    default: Date.now
  },
});

// export the feed object generated by the visualizer form to mongodb
const File = mongoose.model("Image", FileSchema);
module.exports = File;
