import mongoose from 'mongoose'

const ImageUploadSchema = new mongoose.Schema({
  name: {
    type: String
  },
  clientName:{
    type: String
  },
  flightName:{
    type: String
  },
  size: {
    type: String
  },
  blobPath: {
    type: String
  },
  dateUploaded: {
    type: Date,
    default: Date.now
  },
  business: {
    type: String
  },
  metadata: mongoose.Schema.Types.Mixed,
  tags: { type: [String], index: true } 
});


// export the feed object generated by the visualizer form to mongodb
const ImageUpload = mongoose.model("ImageUpload", ImageUploadSchema);
module.exports = ImageUpload;
